General code cleanup and some bugfixing
Jonxslays/Starr pull request #7
Opened 2022-01-28 00:08 UTC by davfsa

2022-01-28 00:47 UTC, Jonxslays requested changes
I like most of this but i think a lot of it will be reformatted when the line length goes back to 99.
I will get around to testing it hopefully by this weekend or tomorrow.

2022-01-28 00:47 UTC, Jonxslays commented on pyproject.toml
> +line-length = 120
I prefer this at 99.

2022-01-28 00:47 UTC, Jonxslays commented on starr/modules/meta.py
> +        color = hikari.Color(0x31A6E0)
:heart:

2022-01-28 11:13 UTC, davfsa commented on pyproject.toml
> +line-length = 120
Was checking hikari's config and just copied it over because for some reason black was skipping formatting. I didnt realize I changed the value, will revert 👍

2022-01-28 11:51 UTC, davfsa commented on starr/data/schema.sql
> -    StarsConfigured INT DEFAULT 0,
Not sure how migrating this will go, but just be aware that you might have to do so

2022-01-28 15:09 UTC, Jonxslays commented on starr/data/schema.sql
> -    StarsConfigured INT DEFAULT 0,
not might, **will** lol. that's ok i was already considering it. thank you for the heads up.

2022-01-28 15:10 UTC, Jonxslays commented on starr/data/schema.sql
> -    StarsConfigured INT DEFAULT 0,
but really just deleting that column from the table and altering the code to not use it should he enough.

2022-01-30 16:56 UTC, Jonxslays requested changes
Few small changes. This is awesome. What you did with the star listeners really cleaned it up I appreciate it.

2022-01-30 16:56 UTC, Jonxslays commented on starr/models.py
> +            (row.add_button(style, f"{self.id_hash}-{key}").set_emoji(button).add_to_container())  # type: ignore
```suggestion
            # The type ignore can be removed when dev 106 releases.
            row.add_button(style, f"{self.id_hash}-{key}").set_emoji(  # type: ignore
                button
            ).add_to_container()
```

2022-01-30 16:56 UTC, Jonxslays commented on starr/models.py
> +            "INSERT INTO starboard_messages (StarMessageID, ReferenceID) VALUES ($1, $2) ON CONFLICT DO NOTHING;",
This has to be split, it fails the CI for len8.

```suggestion
            "INSERT INTO starboard_messages (StarMessageID, ReferenceID) "
            "VALUES ($1, $2) ON CONFLICT DO NOTHING;",
```

2022-01-30 16:56 UTC, Jonxslays commented on starr/modules/help.py
> +                    + f"Subcommands: {', '.join('|'.join(c.names) for c in command.commands)}",
I know I wrote this lol, but lets combine the newline into the f string.

```suggestion
                    + f"\nSubcommands: {', '.join('|'.join(c.names) for c in command.commands)}",
```

2022-01-30 16:56 UTC, Jonxslays commented on starr/modules/tags.py
> -            description=f"Requested tag: `{name}`" "",
wtf

2022-01-30 16:56 UTC, Jonxslays commented on starr/modules/tags.py
> +                    "INSERT INTO tags (GuildID, TagOwner, TagName, TagContent) VALUES ($1, $2, $3, $4);",
Same as above this needs to go to 2 lines because of len8.
```suggestion
                    "INSERT INTO tags (GuildID, TagOwner, TagName, TagContent) "
                    "VALUES ($1, $2, $3, $4);",
```

2022-01-30 17:08 UTC, davfsa commented on starr/modules/meta.py
> +            or "No roles?",
This does 2 roles calles (one done above), they can be merged

2022-01-30 17:08 UTC, davfsa commented on starr/modules/meta.py
Doesnt let me comment further down, prefix and slash commands can be merged (look for more)

2022-01-30 17:08 UTC, davfsa commented on starr/modules/meta.py
>          member = await bot.getch_member(ctx.guild_id, member)
Remove `getch_member` (?)

2022-01-30 17:09 UTC, Jonxslays commented on starr/models.py
> +            (row.add_button(style, f"{self.id_hash}-{key}").set_emoji(button).add_to_container())  # type: ignore
committed locally

2022-01-30 17:09 UTC, Jonxslays commented on starr/models.py
> +            "INSERT INTO starboard_messages (StarMessageID, ReferenceID) VALUES ($1, $2) ON CONFLICT DO NOTHING;",
committed locally

2022-01-30 17:09 UTC, Jonxslays commented on starr/modules/help.py
> +                    + f"Subcommands: {', '.join('|'.join(c.names) for c in command.commands)}",
same

2022-01-30 17:09 UTC, davfsa commented on starr/__main__.py
> +            name="the stars!",
```suggestion
            name="for stars!",
```
Could also be nice

2022-01-30 17:12 UTC, Jonxslays commented on starr/modules/meta.py
> +            or "No roles?",
got this

2022-01-30 17:13 UTC, Jonxslays commented on starr/modules/meta.py
>          member = await bot.getch_member(ctx.guild_id, member)
yep

2022-01-30 17:13 UTC, Jonxslays commented on starr/__main__.py
> +            name="the stars!",
I kinda like watching the stars better

2022-01-30 17:25 UTC, Jonxslays commented on starr/modules/meta.py
I will leave this out for now we can take another look at it later.

2022-01-30 17:31 UTC, Jonxslays approved these changes

2022-01-30 17:33 UTC, merged